sudo: required
services: docker
language: minimal

env:
  - TEST_CASE=1.7
  - TEST_CASE=1.7-flannel
  - TEST_CASE=1.7-calico
  - TEST_CASE=1.7-calico-kdd
  - TEST_CASE=1.7-weave
  - TEST_CASE=1.8
  - TEST_CASE=1.8-flannel
  - TEST_CASE=1.8-calico
  - TEST_CASE=1.8-calico-kdd
  - TEST_CASE=1.8-weave
  - TEST_CASE=1.9
  - TEST_CASE=1.9-flannel
  - TEST_CASE=1.9-calico
  - TEST_CASE=1.9-calico-kdd
  - TEST_CASE=1.9-weave
  - TEST_CASE=src-1.9
    TWAIT=1
  # Temporarily disabling master (14 Feb 2018)
  # The breakage appears to be Travis-specific
  # - TEST_CASE=src-master
  #   TWAIT=1
  # The following tests often don't pass because CNI
  # implementations often aren't up-to-date for k8s master
  # - TEST_CASE=src-master-flannel
  # - TEST_CASE=src-master-calico
  # - TEST_CASE=src-master-calico-kdd
  # - TEST_CASE=src-master-weave

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblz4-tool

script:
  # building k8s may cause Travis to time out w/o output
  - if [ -n "${TWAIT:-}" ]; then travis_wait 35 ./test.sh; else ./test.sh; fi
